import React, { useState } from 'react';
import { Plugs, Plus, Trash, Play, CloudArrowDown, CloudArrowUp, ArrowClockwise, Wrench, Folder, TerminalWindow } from '@phosphor-icons/react';
import { post, remove } from './api';
import { Empty, Modal, Field, ErrorNotice, IconButton, Status } from './ui';

export function McpTools({ connection, notify }) {
  const [tools, setTools] = useState(null); const [selected, setSelected] = useState(null); const [args, setArgs] = useState('{}'); const [result, setResult] = useState(null); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const act = async fn => { setBusy(true); setError(''); try { await fn(); } catch (e) { setError(e.message); } finally { setBusy(false); } };
  return <section className="settings-section"><div className="section-heading"><h3>{connection.name} · MCP 工具</h3><button disabled={busy} onClick={() => act(async () => { const r = await post(`/connections/${connection.id}/mcp/tools`); setTools(r.tools || []); })}><ArrowClockwise size={16} />取得工具清單</button></div><ErrorNotice error={error} />{tools && !tools.length && <p className="muted">此伺服器沒有提供工具。</p>}<div className="mcp-tools">{tools?.map(t => <button className={`mcp-tool ${selected?.name === t.name ? 'selected' : ''}`} key={t.name} onClick={() => { setSelected(t); setArgs('{}'); }}><Wrench size={17} /><span><strong>{t.name}</strong><small>{t.description}</small></span></button>)}</div>{selected && <><h4>{selected.name}</h4><p className="muted">{selected.description}</p><details><summary>參數結構</summary><pre className="diagnostic-output">{JSON.stringify(selected.inputSchema, null, 2)}</pre></details><Field label="工具參數 (JSON)"><textarea className="code-editor config-editor" value={args} onChange={e => setArgs(e.target.value)} /></Field><p className="muted">執行會將參數傳給這個 MCP 伺服器；工具可能修改外部資料。</p><button className="primary" disabled={busy} onClick={() => act(async () => { const r = await post(`/connections/${connection.id}/mcp/call`, { name: selected.name, arguments: JSON.parse(args) }); setResult(r); })}><Play size={16} />執行 {selected.name}</button></>}{result && <pre className="diagnostic-output">{JSON.stringify(result, null, 2)}</pre>}</section>;
}

export function Storage({ connection, project, artifacts, onUpdate, onArtifact }) {
  const [prefix, setPrefix] = useState(''); const [items, setItems] = useState(null); const [key, setKey] = useState(''); const [artifactId, setArtifactId] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [result, setResult] = useState(null);
  const projectArtifacts = artifacts.filter(a => a.projectId === project?.id);
  const act = async fn => { setBusy(true); setError(''); try { await fn(); } catch (e) { setError(e.message); } finally { setBusy(false); } };
  return <section className="settings-section"><h3>{connection.name} · 儲存空間</h3><div className="form-row"><input aria-label="儲存路徑前綴" placeholder="路徑前綴，例如 datasets/" value={prefix} onChange={e => setPrefix(e.target.value)} /><button disabled={busy} onClick={() => act(async () => { const r = await post(`/connections/${connection.id}/storage/list`, { prefix }); setItems(r.items || []); })}><Folder size={16} />列出檔案</button></div><ErrorNotice error={error} /><div className="storage-items">{items?.map((item, i) => { const itemKey = typeof item === 'string' ? item : item.key || item.name || item.Key; return <button key={itemKey || i} onClick={() => setKey(itemKey)} className={key === itemKey ? 'selected' : ''}>{itemKey}</button>; })}</div>{items && !items.length && <p className="muted">此路徑沒有檔案。</p>}<Field label="遠端物件路徑"><input value={key} onChange={e => setKey(e.target.value)} placeholder="資料夾/檔案名稱" /></Field><div className="form-row"><button disabled={!project || !key || busy} onClick={() => act(async () => { const a = await post(`/connections/${connection.id}/storage/download`, { key, projectId: project.id }); await onUpdate(); onArtifact(a); setResult({ downloaded: a.name }); })}><CloudArrowDown size={16} />下載至目前專案</button></div><Field label="上傳專案成果"><select value={artifactId} onChange={e => setArtifactId(e.target.value)}><option value="">選取成果</option>{projectArtifacts.map(a => <option key={a.id} value={a.id}>{a.name}</option>)}</select></Field><button disabled={!artifactId || !key || busy} onClick={() => act(async () => { const r = await post(`/connections/${connection.id}/storage/upload`, { key, artifactId }); setResult(r); })}><CloudArrowUp size={16} />上傳至指定遠端路徑</button>{result && <pre className="diagnostic-output">{JSON.stringify(result, null, 2)}</pre>}</section>;
}
