import React, { useState, useEffect, useCallback, useRef } from 'react';
import { createRoot } from 'react-dom/client';
import { Atom, Plus, MagnifyingGlass, ChatsCircle, Files, Flask, Books, GearSix, SidebarSimple, CaretDown, CaretRight, ArrowUp, Paperclip, TerminalWindow, X, CircleNotch, CheckCircle, WarningCircle, Stop, DownloadSimple, Folder, ArrowRight, ArrowClockwise, DotsThree, UploadSimple, SignIn, Code, Lightbulb, ChartLine, Notebook, ShieldCheck, Command, ArrowsClockwise } from '@phosphor-icons/react';
import { api, post, patch, accountReady, available, date } from './api';
import { IconButton, Markdown, Empty, Loading, ErrorNotice, Modal, Toast, Field, Status } from './ui';
import { ArtifactInspector, ArtifactList, artifactIcon } from './artifacts';
import { ComputePanel, ExecutionConsent } from './compute';
import { Experiments, Literature, Settings } from './pages';
import { Approval, ResearchActivity } from './approvals';
import './styles.css';

const blankState = { projects: [], sessions: [], artifacts: [], runs: [], kernels: [], connections: [], memories: [], settings: {}, account: {}, models: [], capabilities: {}, approvals: [] };
const routes = [['workspace', ChatsCircle, '研究工作區'], ['library', Files, '成果資料庫'], ['experiments', Flask, '實驗與運算'], ['literature', Books, '文獻探索']];

function messageText(message) {
  if (typeof message.text === 'string') return message.text;
  if (typeof message.content === 'string') return message.content;
  if (Array.isArray(message.content)) return message.content.filter(x => x.type === 'text' || x.text).map(x => x.text || '').join('\n');
  return message.output || message.summary || '';
}

function App() {
  const [state, setState] = useState(blankState); const [loading, setLoading] = useState(true); const [connectionError, setConnectionError] = useState(''); const [eventOnline, setEventOnline] = useState(false); const [projectId, setProjectId] = useState(''); const [sessionId, setSessionId] = useState(''); const [session, setSession] = useState(null); const [route, setRoute] = useState('workspace'); const [sideOpen, setSideOpen] = useState(true); const [computeOpen, setComputeOpen] = useState(false); const [tabIds, setTabIds] = useState([]); const [activeArtifact, setActiveArtifact] = useState(''); const [inspectorExpanded, setInspectorExpanded] = useState(false); const [toast, setToast] = useState(null); const [dialog, setDialog] = useState(''); const [search, setSearch] = useState(''); const [busy, setBusy] = useState(false); const [uploading, setUploading] = useState(false); const [attachments, setAttachments] = useState([]); const uploadRef = useRef(); const importRef = useRef(); const projectRef = useRef(projectId); const sessionRef = useRef(sessionId); const inFlight = useRef(null); const refreshAgain = useRef(false);
  projectRef.current = projectId; sessionRef.current = sessionId;
  const notify = useCallback((text, error = false) => setToast({ text, error, id: Date.now() }), []); const closeToast = useCallback(() => setToast(null), []);
  const refresh = useCallback(async () => {
    if (inFlight.current) { refreshAgain.current = true; return inFlight.current; }
    const work = (async () => { try { const data = await api('/state'); setState({ ...blankState, ...data }); setConnectionError(''); const projects = (data.projects || []).filter(p => !p.archived); if (!projectRef.current && projects[0]) setProjectId(projects[0].id); const sid = sessionRef.current; if (sid) { const s = await api(`/sessions/${sid}`); if (sessionRef.current === sid) setSession(s); } } catch (e) { setConnectionError(e.message); } finally { setLoading(false); } })();
    inFlight.current = work; await work; inFlight.current = null; if (refreshAgain.current) { refreshAgain.current = false; return refresh(); }
  }, []);
  useEffect(() => { refresh(); let timer; const events = new EventSource('/api/events'); const changed = () => { clearTimeout(timer); timer = setTimeout(refresh, 180); }; events.addEventListener('update', changed); events.onmessage = changed; events.onopen = () => setEventOnline(true); events.onerror = () => setEventOnline(false); const poll = setInterval(refresh, 15000); return () => { clearTimeout(timer); clearInterval(poll); events.close(); }; }, [refresh]);
  useEffect(() => { let live = true; setSession(null); if (sessionId) api(`/sessions/${sessionId}`).then(s => { if (live) setSession(s); }).catch(e => live && notify(e.message, true)); return () => { live = false; }; }, [sessionId, notify]);
  useEffect(() => { const handler = e => { if ((e.ctrlKey || e.metaKey) && e.key.toLowerCase() === 'k') { e.preventDefault(); setDialog('search'); } if ((e.ctrlKey || e.metaKey) && e.key.toLowerCase() === 'j') { e.preventDefault(); setComputeOpen(v => !v); setRoute('workspace'); } }; window.addEventListener('keydown', handler); return () => window.removeEventListener('keydown', handler); }, []);
  const project = state.projects.find(p => p.id === projectId); const projectArtifacts = state.artifacts.filter(a => a.projectId === projectId); const projectSessions = state.sessions.filter(s => s.projectId === projectId); const activeRuns = state.runs.filter(r => ['running', 'queued'].includes(r.status)); const ready = accountReady(state.account); const account = state.account?.account || state.account; const pendingApprovals = (state.approvals || []).filter(a => !a.status || ['pending', 'requested'].includes(a.status));
  const changeProject = id => { setProjectId(id); setSessionId(''); setSession(null); setTabIds([]); setActiveArtifact(''); setAttachments([]); setInspectorExpanded(false); };
  const openArtifact = a => { if (!a?.id) return; if (a.projectId && a.projectId !== projectRef.current) changeProject(a.projectId); setTabIds(ids => ids.includes(a.id) ? ids : [...ids, a.id]); setActiveArtifact(a.id); setRoute('workspace'); };
  const closeArtifact = id => { setTabIds(ids => { const next = ids.filter(x => x !== id); if (activeArtifact === id) setActiveArtifact(next.at(-1) || ''); return next; }); };
  const newSession = async () => { if (!project) { setDialog('project'); return; } setBusy(true); try { const s = await post('/sessions', { projectId, title: '新的研究' }); setSessionId(s.id); setSession(s); setRoute('workspace'); setAttachments([]); await refresh(); return s; } catch (e) { notify(e.message, true); } finally { setBusy(false); } };
  const upload = async files => { if (!files?.length) return; if (!project) { notify('請先建立專案，再匯入檔案', true); setDialog('project'); return; } setUploading(true); try { const body = new FormData(); body.append('projectId', projectId); if (sessionId) body.append('sessionId', sessionId); for (const f of files) body.append('files', f); const result = await api('/artifacts/upload', { method: 'POST', body }); const artifacts = Array.isArray(result) ? result : result.artifacts || []; await refresh(); setAttachments(prev => [...new Set([...prev, ...artifacts.map(a => a.id)])]); if (artifacts[0]) openArtifact(artifacts[0]); notify(`已匯入 ${artifacts.length} 個檔案`); } catch (e) { notify(e.message, true); } finally { setUploading(false); if (uploadRef.current) uploadRef.current.value = ''; } };
  const onReview = id => { setSessionId(id); setRoute('workspace'); setInspectorExpanded(false); refresh(); };
  const shared = { state, project, sessionId, onUpdate: refresh, notify, onArtifact: openArtifact };
  return <div className={`app ${sideOpen ? '' : 'sidebar-collapsed'}`}><input type="file" ref={uploadRef} multiple hidden onChange={e => upload(e.target.files)} /><input type="file" ref={importRef} accept=".json,application/json" hidden onChange={async e => { const file = e.target.files?.[0]; if (!file) return; try { const packageData = JSON.parse(await file.text()); const p = await post('/projects/import', packageData); await refresh(); changeProject(p.id); notify('研究專案已匯入'); } catch (err) { notify(err.message, true); } finally { e.target.value = ''; } }} />
    {sideOpen && <aside className="sidebar"><div className="brand"><div className="brand-symbol"><Atom size={24} weight="light" /></div><div><strong>ChatGPT Science</strong><span>獨立研究工作台</span></div><IconButton icon={SidebarSimple} label="收合側邊欄" onClick={() => setSideOpen(false)} /></div><div className="project-picker"><Folder size={18} /><select aria-label="目前專案" value={projectId} onChange={e => changeProject(e.target.value)}><option value="" disabled>選擇研究專案</option>{state.projects.filter(p => !p.archived).map(p => <option value={p.id} key={p.id}>{p.name}</option>)}</select><IconButton icon={DotsThree} label="管理專案" onClick={() => setDialog('project-manage')} /></div><button className="new-research" onClick={newSession} disabled={busy}><Plus size={18} />新的研究</button><button className="sidebar-search" onClick={() => setDialog('search')}><MagnifyingGlass size={17} /><span>搜尋工作台</span><kbd>Ctrl K</kbd></button><nav className="main-nav" aria-label="主選單">{routes.map(([key, Icon, label]) => <button className={route === key ? 'active' : ''} key={key} onClick={() => setRoute(key)}><Icon size={19} weight={route === key ? 'fill' : 'regular'} /><span>{label}</span>{key === 'library' && projectArtifacts.length > 0 && <small>{projectArtifacts.length}</small>}{key === 'experiments' && activeRuns.length > 0 && <span className="running-dot" />}</button>)}</nav><div className="recent-header"><span>研究對話</span><IconButton icon={Plus} label="新增研究對話" onClick={newSession} /></div><div className="session-list">{projectSessions.length ? [...projectSessions].reverse().map(s => <button key={s.id} className={sessionId === s.id && route === 'workspace' ? 'active' : ''} onClick={() => { setSessionId(s.id); setRoute('workspace'); setInspectorExpanded(false); setAttachments([]); }}><ChatsCircle size={15} /><span>{s.title || '未命名研究'}</span>{['running', 'busy'].includes(s.status) && <CircleNotch size={14} className="spin" />}</button>) : <p className="sidebar-empty">從一個問題開始。<br />研究過程會保存在這裡。</p>}</div><div className="sidebar-bottom"><button onClick={() => setDialog('project')}><Plus size={17} />建立新專案</button><button className={route === 'settings' ? 'active' : ''} onClick={() => setRoute('settings')}><GearSix size={18} />設定</button><button className="sidebar-account" onClick={() => setRoute('settings')}><div className="avatar">{ready ? (account?.email?.[0]?.toUpperCase() || 'G') : <SignIn size={17} />}</div><span><strong>{ready ? account?.email || 'ChatGPT 帳號' : '連接 ChatGPT'}</strong><small>{ready ? account?.planType || '已登入' : '設定你的研究助手'}</small></span><CaretRight size={14} /></button></div></aside>}
    <main className="main-shell"><header className="topbar"><div className="breadcrumbs">{!sideOpen && <IconButton icon={SidebarSimple} label="展開側邊欄" onClick={() => setSideOpen(true)} />}<Folder size={16} /><span>{project?.name || '研究工作台'}</span><CaretRight size={12} /><strong>{route === 'workspace' ? session?.title || '新的研究' : route === 'settings' ? '設定' : routes.find(r => r[0] === route)?.[2]}</strong></div><div className="topbar-actions"><span className={`live-connection ${eventOnline ? 'online' : ''}`} title={eventOnline ? '與本機服務保持連線' : '正在重新連線'}><i />{eventOnline ? '本機已連線' : '重新連線中'}</span><IconButton icon={ArrowClockwise} label="重新整理狀態" onClick={refresh} />{project && <a className="icon-button" title="匯出研究專案" aria-label="匯出研究專案" href={`/api/projects/${project.id}/export`}><DownloadSimple size={18} /></a>}<button className={`compute-toggle ${computeOpen ? 'active' : ''}`} onClick={() => { setComputeOpen(!computeOpen); setRoute('workspace'); }}><TerminalWindow size={17} /><span>運算</span>{activeRuns.length > 0 && <small>{activeRuns.length}</small>}</button></div></header>
    <ErrorNotice error={connectionError} retry={refresh} />{pendingApprovals.length > 0 && <div className="approval-stack">{pendingApprovals.map(a => <Approval key={a.id} approval={a} onUpdate={refresh} notify={notify} />)}</div>}
    {loading ? <div className="app-loading"><Atom size={37} weight="light" /><Loading label="載入研究工作台…" /></div> : route === 'workspace' ? <div className="workspace"><div className={`workspace-main ${inspectorExpanded ? 'expanded-artifact' : ''}`}><div className="conversation-column">{!project ? <FirstProject onCreate={() => setDialog('project')} onImport={() => importRef.current?.click()} /> : <Conversation {...shared} session={session} sessionId={sessionId} setSession={setSession} setSessionId={setSessionId} busy={busy} setBusy={setBusy} newSession={newSession} attachments={attachments} setAttachments={setAttachments} upload={() => uploadRef.current?.click()} uploading={uploading} openSettings={() => setRoute('settings')} />}</div><ArtifactInspector artifacts={projectArtifacts} tabIds={tabIds} activeId={activeArtifact} onOpen={openArtifact} onClose={closeArtifact} onActivate={setActiveArtifact} onUpload={() => uploadRef.current?.click()} onUpdate={refresh} onReview={onReview} notify={notify} expanded={inspectorExpanded} onExpand={() => setInspectorExpanded(v => !v)} /></div>{computeOpen && <ComputePanel {...shared} onToggle={() => setComputeOpen(false)} />}</div> : route === 'library' ? <div className="library-page page-scroll"><div className="section-heading"><div><span className="eyebrow">專案成果</span><h1>成果資料庫</h1><p className="muted">資料、程式碼與研究結果，保留每一次演進。</p></div><button className="primary" onClick={() => uploadRef.current?.click()} disabled={uploading}><UploadSimple size={17} />{uploading ? '正在匯入…' : '匯入檔案'}</button></div><ArtifactList artifacts={projectArtifacts} onOpen={openArtifact} onUpload={() => uploadRef.current?.click()} /></div> : route === 'experiments' ? <Experiments {...shared} /> : route === 'literature' ? <Literature {...shared} /> : <Settings {...shared} />}
    <footer className="statusbar"><span><i className={eventOnline ? 'online-dot' : ''} />{project ? `${projectArtifacts.length} 個成果 · ${projectSessions.length} 個研究對話` : '尚未選取研究專案'}</span><div><span>Python {available(state.capabilities.python) ? '可用' : '未就緒'}</span><span>R {available(state.capabilities.r) ? '可用' : '未就緒'}</span><button onClick={() => setRoute('settings')}>{ready ? 'ChatGPT 已連線' : 'ChatGPT 尚未登入'}</button></div></footer></main>
    {dialog === 'project' && <ProjectModal onClose={() => setDialog('')} onCreate={async values => { const p = await post('/projects', values); await refresh(); changeProject(p.id); setRoute('workspace'); setDialog(''); notify('研究專案已建立'); }} />}
    {dialog === 'project-manage' && <Modal title="管理研究專案" onClose={() => setDialog('')}><div className="project-actions"><button onClick={() => setDialog('project')}><Plus size={17} />建立新專案</button><button onClick={() => { setDialog(''); importRef.current?.click(); }}><UploadSimple size={17} />匯入研究封存</button></div>{project && <ProjectEdit project={project} onSave={async values => { await patch(`/projects/${project.id}`, values); await refresh(); setDialog(''); notify('專案設定已更新'); }} notify={notify} />}</Modal>}
    {dialog === 'search' && <Modal title="搜尋工作台" onClose={() => setDialog('')} wide><div className="search-input global-search"><MagnifyingGlass size={19} /><input autoFocus value={search} onChange={e => setSearch(e.target.value)} placeholder="搜尋專案、研究對話與成果…" aria-label="搜尋工作台" /></div><div className="search-results">{state.projects.filter(p => p.name.toLowerCase().includes(search.toLowerCase())).map(p => <button key={p.id} onClick={() => { changeProject(p.id); setRoute('workspace'); setDialog(''); }}><Folder size={18} /><span>{p.name}</span><small>專案</small></button>)}{state.sessions.filter(s => s.title?.toLowerCase().includes(search.toLowerCase())).slice(0, 15).map(s => <button key={s.id} onClick={() => { if (s.projectId !== projectId) changeProject(s.projectId); setSessionId(s.id); setRoute('workspace'); setDialog(''); }}><ChatsCircle size={18} /><span>{s.title}</span><small>對話</small></button>)}{state.artifacts.filter(a => a.name.toLowerCase().includes(search.toLowerCase())).slice(0, 20).map(a => { const Icon = artifactIcon(a); return <button key={a.id} onClick={() => { openArtifact(a); setDialog(''); }}><Icon size={18} /><span>{a.name}</span><small>成果</small></button>; })}</div></Modal>}
    <Toast toast={toast} close={closeToast} />
  </div>;
}

function FirstProject({ onCreate, onImport }) { return <div className="first-project"><div className="research-mark"><Atom size={49} weight="thin" /></div><span className="eyebrow">你的研究空間</span><h1>讓下一個問題，<br />成為新的發現。</h1><p>在同一個工作台中與 ChatGPT 討論、執行實驗、檢視結果，保存可追溯的研究過程。</p><button className="primary" onClick={onCreate}><Plus size={17} />建立第一個研究專案</button><button className="text-button import-link" onClick={onImport}>匯入已有專案 <ArrowRight size={15} /></button><div className="first-project-note"><span><Code size={17} />Python 與 R</span><span><Files size={17} />版本與來源</span><span><ShieldCheck size={17} />研究審查</span></div></div>; }

function Conversation({ state, project, session, sessionId, setSession, setSessionId, onUpdate, notify, busy, setBusy, attachments, setAttachments, upload, uploading, openSettings }) {
  const [draft, setDraft] = useState(''); const [model, setModel] = useState(''); const [error, setError] = useState(''); const end = useRef(); const scroll = useRef(); const follow = useRef(true); const input = useRef(); const ready = accountReady(state.account); const context = useRef({ projectId: project.id, sessionId }); context.current = { projectId: project.id, sessionId }; const sessionLoading = !!sessionId && session?.id !== sessionId; const running = ['running', 'busy', 'starting', 'stopping', 'inProgress'].includes(session?.status); const messages = session?.messages || [];
  useEffect(() => { setDraft(''); setError(''); follow.current = true; }, [sessionId, project.id]);
  useEffect(() => { if (follow.current) end.current?.scrollIntoView({ block: 'end', behavior: 'instant' }); }, [JSON.stringify(messages)]);
  useEffect(() => { if (state.models?.length && !state.models.some(m => (m.id || m.model) === model)) { const preferred = state.models.find(m => m.isDefault) || state.models[0]; setModel(preferred.id || preferred.model); } }, [state.models, model]);
  const send = async () => {
    if (!draft.trim() || busy || running || !ready || sessionLoading) return;
    const requestContext = { projectId: project.id, sessionId };
    const text = draft; const attachmentIds = [...attachments];
    let target = session;
    const stillHere = () => context.current.projectId === requestContext.projectId && [requestContext.sessionId, target?.id].includes(context.current.sessionId);
    setBusy(true); setError('');
    try {
      if (!target) {
        target = await post('/sessions', { projectId: requestContext.projectId, title: text.slice(0, 45) });
        if (stillHere()) { setSessionId(target.id); setSession(target); }
      }
      await post(`/sessions/${target.id}/message`, { text, model: model || undefined, attachmentIds });
      if (stillHere()) { setDraft(''); setAttachments([]); follow.current = true; }
      await onUpdate();
    } catch (e) {
      if (stillHere()) { setError(e.message); setDraft(text); }
      else notify(e.message, true);
    } finally { setBusy(false); }
  };
  const suggestions = [
    [Lightbulb, '把研究想法變成實驗', '幫我把研究問題拆成可驗證的假設、基準實驗與評估指標。先確認我已有的資料與運算資源。'],
    [ChartLine, '分析資料與建立圖表', '協助我檢查上傳資料的品質，設計分析流程，並產生可重現的程式碼與圖表。'],
    [Books, '讀懂方法與比較文獻', '協助我比較這個研究方向的相關方法，核對來源，整理已知限制與可驗證的研究空缺。'],
    [Flask, '重現論文與消融實驗', '協助我重現論文結果，先盤點程式碼與環境需求，再建立基準、消融設計與可追溯的執行紀錄。'],
  ];
  return <div className="conversation"><div className="chat-scroll" ref={scroll} onScroll={e => { const el = e.currentTarget; follow.current = el.scrollHeight - el.scrollTop - el.clientHeight < 120; }}>{messages.length === 0 ? <div className="welcome"><div className="welcome-top"><Atom size={35} weight="thin" /><span>新的研究</span></div><h1>你想探索什麼？</h1><p>提出問題、帶入資料，讓想法一步步成為<br className="wide-only" />可檢查、可重現的研究成果。</p><div className="prompt-suggestions">{suggestions.map(([Icon, title, text]) => <button key={title} onClick={() => { setDraft(text); input.current?.focus(); }}><Icon size={21} weight="light" /><span>{title}</span><ArrowRight size={16} /></button>)}</div><div className="welcome-context"><Folder size={14} /><span>{project.name}</span><span>·</span><span>{state.artifacts.filter(a => a.projectId === project.id).length} 個專案檔案</span></div></div> : <div className="messages">{messages.map((m, i) => <Message key={m.id || i} message={m} />)}<ResearchActivity session={session} />{running && <div className="thinking-indicator"><CircleNotch className="spin" size={16} /><span>正在研究…</span></div>}<div ref={end} /></div>}</div>
    <div className="composer-area">{!ready && <div className="account-hint"><SignIn size={16} /><span>連接 ChatGPT 帳號，開始研究對話。</span><button onClick={openSettings}>設定帳號 <ArrowRight size={14} /></button></div>}<ErrorNotice error={error} />{attachments.length > 0 && <div className="attachment-chips">{attachments.map(id => { const a = state.artifacts.find(a => a.id === id); return <span key={id}><Paperclip size={14} />{a?.name || '檔案'}<button aria-label="移除附件" onClick={() => setAttachments(ids => ids.filter(x => x !== id))}><X size={12} /></button></span>; })}</div>}<div className={`composer ${!ready ? 'composer-disabled' : ''}`} onDragOver={e => e.preventDefault()}><textarea ref={input} value={draft} onChange={e => setDraft(e.target.value)} placeholder="描述你的研究問題，或加入資料開始分析…" aria-label="研究訊息" rows={3} onKeyDown={e => { if (e.key === 'Enter' && !e.shiftKey && !e.nativeEvent.isComposing) { e.preventDefault(); send(); } }} /><div className="composer-tools"><IconButton icon={uploading ? CircleNotch : Paperclip} className={uploading ? 'spin' : ''} label="附加研究檔案" disabled={uploading} onClick={upload} /><select aria-label="對話模型" value={model} onChange={e => setModel(e.target.value)} disabled={!state.models?.length}><option value="" disabled>{state.models?.length ? '選擇模型' : '登入後選擇模型'}</option>{state.models?.map(m => <option value={m.id || m.model} key={m.id || m.model}>{m.displayName || m.id || m.model}</option>)}</select><span className="spacer" />{running ? <button className="send-button stop-button" title="停止研究" aria-label="停止研究" onClick={async () => { try { await post(`/sessions/${sessionId}/interrupt`); await onUpdate(); } catch (e) { notify(e.message, true); } }}><Stop size={18} weight="fill" /></button> : <button className="send-button" aria-label="送出研究訊息" title="送出研究訊息" disabled={!draft.trim() || busy || !ready || sessionLoading} onClick={send}>{busy ? <CircleNotch className="spin" size={19} /> : <ArrowUp size={20} weight="bold" />}</button>}</div></div><div className="composer-footnote"><span>結果與引用仍需查核；保留程式與來源有助於重現。</span><span>Shift + Enter 換行</span></div></div>
  </div>;
}

function Message({ message }) {
  const role = message.role || (message.type?.includes('tool') ? 'tool' : 'assistant'); const text = messageText(message);
  if (role === 'tool' || ['tool_call', 'command', 'tool'].includes(message.type)) return <details className="tool-message"><summary><TerminalWindow size={16} /><span>{message.name || message.title || '執行研究工具'}</span>{message.status && <Status value={message.status} />}</summary>{message.command && <pre>{Array.isArray(message.command) ? message.command.join(' ') : message.command}</pre>}<pre>{typeof text === 'string' ? text : JSON.stringify(text, null, 2)}</pre></details>;
  return <article className={`message message-${role}`}><div className="message-role">{role === 'user' ? <div className="message-avatar user-avatar">你</div> : <Atom size={22} weight="light" />}<strong>{role === 'user' ? '你' : role === 'system' ? '研究紀錄' : '研究助手'}</strong>{message.createdAt && <time>{date(message.createdAt)}</time>}</div><div className="message-content"><Markdown text={text} />{message.attachments?.length > 0 && <div className="attachment-chips">{message.attachments.map((a, i) => <span key={a.id || i}><Paperclip size={13} />{a.name || a}</span>)}</div>}{message.status === 'error' && <div className="error-notice">{message.error || '這次回覆未能完成。'}</div>}</div></article>;
}

function ProjectModal({ onClose, onCreate }) { const [name, setName] = useState(''); const [description, setDescription] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); return <Modal title="建立研究專案" onClose={onClose}><p className="muted">為一個研究問題建立空間，集中保存對話、資料與實驗結果。</p><Field label="專案名稱"><input autoFocus value={name} onChange={e => setName(e.target.value)} placeholder="例如：小型語言模型的推理效率" onKeyDown={e => { if (e.key === 'Enter' && name.trim()) e.currentTarget.form?.requestSubmit(); }} /></Field><Field label="研究目標（選填）"><textarea value={description} onChange={e => setDescription(e.target.value)} placeholder="你想回答什麼問題？有哪些限制或已知條件？" rows={4} /></Field><ErrorNotice error={error} /><div className="modal-actions"><button onClick={onClose}>取消</button><button className="primary" disabled={!name.trim() || busy} onClick={async () => { setBusy(true); try { await onCreate({ name: name.trim(), description }); } catch (e) { setError(e.message); setBusy(false); } }}>{busy ? '建立中…' : '建立專案'}</button></div></Modal>; }

function ProjectEdit({ project, onSave, notify }) { const [name, setName] = useState(project.name); const [description, setDescription] = useState(project.description || ''); const [busy, setBusy] = useState(false); return <div className="settings-section"><Field label="專案名稱"><input value={name} onChange={e => setName(e.target.value)} /></Field><Field label="研究目標"><textarea rows={3} value={description} onChange={e => setDescription(e.target.value)} /></Field><small className="muted wrap-anywhere">{project.root}</small><div className="modal-actions"><button className="primary" disabled={!name.trim() || busy} onClick={async () => { setBusy(true); try { await onSave({ name, description }); } catch (e) { notify(e.message, true); setBusy(false); } }}>儲存專案</button></div></div>; }

class ErrorBoundary extends React.Component { constructor(props) { super(props); this.state = { error: null }; } static getDerivedStateFromError(error) { return { error }; } render() { if (this.state.error) return <div className="fatal-error"><WarningCircle size={34} /><h1>工作台遇到顯示問題</h1><p>{this.state.error.message}</p><button className="primary" onClick={() => window.location.reload()}>重新載入工作台</button></div>; return this.props.children; } }

createRoot(document.getElementById('root')).render(<ErrorBoundary><App /></ErrorBoundary>);
