import React, { useState, useEffect } from 'react';
import { MagnifyingGlass, Books, Plus, ArrowSquareOut, CircleNotch, BookmarkSimple, Trash, PuzzlePiece, SignIn, CheckCircle, Cpu, Flask, Package, Globe, Plugs, GearSix, Notebook, DownloadSimple, ArrowClockwise, UploadSimple, GitDiff } from '@phosphor-icons/react';
import { api, post, patch, remove, accountReady, available, capabilityReason, date } from './api';
import { Empty, Loading, ErrorNotice, Markdown, ExternalLink, Field, Modal, IconButton, Status } from './ui';
import { ComputePanel, Environments, RemoteCompute, ExecutionConsent } from './compute';
import { Connections } from './connection-manager';
import { AccountPanel } from './account';

export function Literature({ project, onArtifact, onUpdate, notify }) {
  const [query, setQuery] = useState(''); const [results, setResults] = useState(null); const [busy, setBusy] = useState(false); const [savingId, setSavingId] = useState(''); const [saved, setSaved] = useState(new Set()); const [error, setError] = useState('');
  const search = async () => { if (!query.trim()) return; setBusy(true); setError(''); try { const result = await post('/literature/search', { query }); setResults(result.results || []); } catch (e) { setError(e.message); } finally { setBusy(false); } };
  return <div className="page-scroll literature-page"><div className="page-title"><span className="eyebrow">文獻探索</span><h1>從可靠的來源，展開研究。</h1><p>搜尋論文、查看摘要，並將參考文獻保存到目前專案。</p></div><div className="literature-search"><MagnifyingGlass size={21} /><input aria-label="搜尋研究文獻" value={query} onChange={e => setQuery(e.target.value)} onKeyDown={e => e.key === 'Enter' && search()} placeholder="輸入研究問題、關鍵字或論文標題" /><button className="primary" disabled={busy || !query.trim()} onClick={search}>{busy ? <CircleNotch className="spin" size={18} /> : '搜尋'}</button></div><ErrorNotice error={error} />{busy ? <Loading label="搜尋文獻來源…" /> : results === null ? <Empty icon={Books} title="為研究建立文獻脈絡">用具體的主題或方法名稱搜尋，例如「transformer mechanistic interpretability」。</Empty> : !results.length ? <Empty icon={MagnifyingGlass} title="沒有找到符合的文獻">試著縮短搜尋條件，或換成英文關鍵字。</Empty> : <><div className="results-count">找到 {results.length} 篇文獻</div><div className="literature-results">{results.map((r, i) => { const id = r.id || r.doi || r.url || String(i); return <article key={id}><div className="paper-meta"><span>{r.year || '年份未知'}</span><span>{r.source || r.venue || '學術文獻'}</span></div><h2><ExternalLink href={r.url || (r.doi ? `https://doi.org/${r.doi}` : '')}>{r.title}</ExternalLink></h2><p className="paper-authors">{Array.isArray(r.authors) ? r.authors.map(a => typeof a === 'string' ? a : a.name).join(', ') : r.authors}</p>{r.abstract && <details><summary>閱讀摘要</summary><p className="paper-abstract">{r.abstract}</p></details>}<div className="paper-actions">{r.doi && <small className="mono">DOI: {r.doi}</small>}<span className="spacer" /><button disabled={!project || savingId === id || saved.has(id)} onClick={async () => { setSavingId(id); try { const a = await post('/literature/save', { projectId: project.id, result: r }); setSaved(s => new Set([...s, id])); await onUpdate(); notify('文獻已保存至專案'); } catch (e) { notify(e.message, true); } finally { setSavingId(''); } }}><BookmarkSimple size={16} weight={saved.has(id) ? 'fill' : 'regular'} />{saved.has(id) ? '已保存' : savingId === id ? '保存中…' : '保存至專案'}</button></div></article>; })}</div></>}</div>;
}

function RunComparison({ state, project }) {
  const runs = (state.runs || []).filter(r => r.projectId === project?.id); const [left, setLeft] = useState(''); const [right, setRight] = useState(''); const [details, setDetails] = useState([]); const [error, setError] = useState('');
  useEffect(() => { let live = true; const ids = [runs.some(r => r.id === left) ? left : runs[0]?.id, runs.some(r => r.id === right) ? right : runs[1]?.id]; if (ids.some(id => !id)) { setDetails([]); return; } Promise.all(ids.map(id => api(`/runs/${id}`))).then(r => live && setDetails(r)).catch(e => live && setError(e.message)); return () => { live = false; }; }, [left, right, project?.id, runs[0]?.id, runs[1]?.id, JSON.stringify(runs.filter(r => [left, right, runs[0]?.id, runs[1]?.id].includes(r.id)).map(r => [r.id, r.status, r.endedAt, r.outputs?.length, r.outputs?.at(-1)?.text?.length]))]);
  const metrics = run => { const found = {}; for (const output of run.outputs || []) { let data = output.data?.['application/json']; if (!data && output.text) { try { data = JSON.parse(output.text); } catch {} } if (data && typeof data === 'object' && !Array.isArray(data)) for (const [k, v] of Object.entries(data)) if (typeof v === 'number') found[k] = v; } return found; };
  const shownDetails = details.filter(r => r.projectId === project?.id); const a = shownDetails[0] ? metrics(shownDetails[0]) : {}; const b = shownDetails[1] ? metrics(shownDetails[1]) : {}; const keys = [...new Set([...Object.keys(a), ...Object.keys(b)])];
  return <div className="comparison-page"><div className="section-intro"><h3>實驗比較</h3><p>並排檢查兩次執行的程式碼、環境及數值輸出。消融條件可直接保留在程式碼與專案記憶中。</p></div>{runs.length < 2 ? <Empty icon={GitDiff} title="累積兩次執行後開始比較">在 Python 或 R 中輸出 JSON 指標，可在此自動比較數值。</Empty> : <><div className="comparison-selectors">{[[runs.some(r => r.id === left) ? left : runs[0]?.id, setLeft, '基準實驗'], [runs.some(r => r.id === right) ? right : runs[1]?.id, setRight, '比較實驗']].map(([value, setter, label]) => <Field label={label} key={label}><select value={value} onChange={e => setter(e.target.value)}>{runs.map((r, i) => <option key={r.id} value={r.id}>#{i + 1} · {date(r.startedAt)} · {r.status}</option>)}</select></Field>)}</div><ErrorNotice error={error} />{keys.length > 0 && <div className="table-scroll"><table><thead><tr><th>輸出指標</th><th>基準</th><th>比較</th><th>差值</th></tr></thead><tbody>{keys.map(k => <tr key={k}><td>{k}</td><td>{a[k] ?? '未輸出'}</td><td>{b[k] ?? '未輸出'}</td><td>{a[k] !== undefined && b[k] !== undefined ? Number((b[k] - a[k]).toPrecision(8)) : '無法比較'}</td></tr>)}</tbody></table></div>}<div className="comparison-grid">{shownDetails.map((run, i) => <section key={i}><div className="run-meta"><Status value={run.status} /><span>{run.endedAt ? `${((new Date(run.endedAt) - new Date(run.startedAt)) / 1000).toFixed(2)} 秒` : '執行中'}</span></div><h4>程式碼</h4><pre className="source-code">{run.code}</pre><h4>環境</h4><pre className="source-code">{JSON.stringify(run.environment, null, 2)}</pre></section>)}</div></>}</div>;
}

export function Experiments(props) { const [tab, setTab] = useState('console'); return <div className="experiments-page"><div className="page-tabs">{[['console', TerminalIcon, '互動運算'], ['compare', GitDiff, '實驗比較'], ['environments', Package, '套件與環境'], ['remote', Globe, '遠端作業']].map(([key, Icon, label]) => <button className={tab === key ? 'active' : ''} key={key} onClick={() => setTab(key)}><Icon size={17} />{label}</button>)}</div>{tab === 'console' ? <ComputePanel {...props} expanded /> : <div className="page-scroll">{tab === 'compare' ? <RunComparison {...props} /> : tab === 'environments' ? <Environments {...props} /> : <RemoteCompute {...props} />}</div>}</div>; }
const TerminalIcon = Cpu;

function Memories({ state, project, notify, onUpdate }) { const [text, setText] = useState(''); const [busy, setBusy] = useState(false); const memories = (state.memories || []).filter(m => m.projectId === project?.id); return <div><div className="section-intro"><h2>專案記憶</h2><p>保存研究目標、資料定義與方法限制，提供給後續研究對話。</p></div><Field label="新增研究備註"><textarea value={text} onChange={e => setText(e.target.value)} placeholder="例如：所有模型都使用相同資料切分；報告平均值與標準差。" rows={5} /></Field><button className="primary" disabled={!project || !text.trim() || busy} onClick={async () => { setBusy(true); try { await post('/memories', { projectId: project.id, text }); setText(''); await onUpdate(); } catch (e) { notify(e.message, true); } finally { setBusy(false); } }}><Plus size={16} />儲存記憶</button><div className="memory-list">{memories.map(m => <article key={m.id}><div><small>{date(m.createdAt)}</small><p>{m.text}</p></div><IconButton icon={Trash} label="刪除這則記憶" onClick={async () => { try { await remove(`/memories/${m.id}`); await onUpdate(); } catch (e) { notify(e.message, true); } }} /></article>)}</div></div>; }

function Skills({ notify }) { const [skills, setSkills] = useState(null); const [error, setError] = useState(''); const [name, setName] = useState(''); const [description, setDescription] = useState(''); const [instructions, setInstructions] = useState(''); const [adding, setAdding] = useState(false); const [busy, setBusy] = useState(false); const load = async () => { try { const d = await api('/skills'); setSkills(Array.isArray(d) ? d : d.skills || []); } catch (e) { setError(e.message); } }; useEffect(() => { load(); }, []); return <div><div className="section-heading"><div><h2>研究技能</h2><p className="muted">建立可重用的分析流程與審查指引。</p></div><button onClick={() => setAdding(true)}><Plus size={16} />建立技能</button></div><ErrorNotice error={error} retry={load} />{skills === null && !error ? <Loading /> : skills?.length ? <div className="skill-list">{skills.map((s, i) => <article key={s.id || s.name || i}><PuzzlePiece size={22} /><div><strong>{s.name}</strong><p>{s.description}</p><small>{s.source || s.path || ''}</small></div></article>)}</div> : <Empty icon={PuzzlePiece} title="尚無研究技能">將常用的研究步驟整理為技能，在新對話中重複使用。</Empty>}{adding && <Modal title="建立研究技能" onClose={() => setAdding(false)} wide><Field label="技能名稱"><input value={name} onChange={e => setName(e.target.value)} placeholder="例如 experiment-review" /></Field><Field label="用途說明"><input value={description} onChange={e => setDescription(e.target.value)} /></Field><Field label="完整操作指引"><textarea className="code-editor config-editor" value={instructions} onChange={e => setInstructions(e.target.value)} placeholder="描述使用時機、必要輸入、執行步驟與驗收條件…" /></Field><p className="muted">技能儲存在此工作台的專屬目錄。</p><div className="modal-actions"><button onClick={() => setAdding(false)}>取消</button><button className="primary" disabled={!name.trim() || !instructions.trim() || busy} onClick={async () => { setBusy(true); try { await post('/skills', { name, description, instructions }); await load(); setAdding(false); setName(''); setInstructions(''); notify('研究技能已建立'); } catch (e) { setError(e.message); } finally { setBusy(false); } }}>建立技能</button></div><ErrorNotice error={error} /></Modal>}</div>; }

function Preferences({ state, project, onUpdate, notify }) {
  const [draft, setDraft] = useState(state.settings || {}); const [busy, setBusy] = useState(false);
  useEffect(() => { setDraft(state.settings || {}); }, [JSON.stringify(state.settings)]);
  return <div><div className="section-intro"><h2>工作台設定</h2><p>管理本機運算路徑與執行限制。</p></div><ExecutionConsent project={project} onUpdate={onUpdate} notify={notify} /><div className="settings-fields"><Field label="Python 執行檔路徑" hint="留白使用自動偵測。"><input value={draft.pythonPath || ''} onChange={e => setDraft({ ...draft, pythonPath: e.target.value })} placeholder="自動偵測" /></Field><Field label="R 執行檔路徑" hint="需有可用的 IRkernel。"><input value={draft.rPath || ''} onChange={e => setDraft({ ...draft, rPath: e.target.value })} placeholder="自動偵測" /></Field><div className="form-row"><Field label="每次執行最長秒數"><input type="number" min="1" max="86400" value={draft.maxRuntimeSeconds ?? 120} onChange={e => setDraft({ ...draft, maxRuntimeSeconds: Number(e.target.value) })} /></Field><Field label="同時執行數"><input type="number" min="1" max="16" value={draft.maxConcurrentRuns ?? 2} onChange={e => setDraft({ ...draft, maxConcurrentRuns: Number(e.target.value) })} /></Field><Field label="最多重試次數"><input type="number" min="0" max="10" value={draft.maxRetries ?? 0} onChange={e => setDraft({ ...draft, maxRetries: Number(e.target.value) })} /></Field></div><button className="primary" disabled={busy} onClick={async () => { setBusy(true); try { await patch('/settings', draft); await onUpdate(); notify('設定已儲存'); } catch (e) { notify(e.message, true); } finally { setBusy(false); } }}>儲存設定</button></div><div className="settings-section"><h3>專案資料</h3><p className="muted">匯出包含專案紀錄與成果的可攜式研究封存。</p><a className={`button ${!project ? 'disabled' : ''}`} href={project ? `/api/projects/${project.id}/export` : undefined}><DownloadSimple size={16} />匯出目前專案</a></div></div>;
}

export function Settings(props) { const [tab, setTab] = useState('account'); return <div className="settings-layout"><nav className="settings-nav" aria-label="設定分類">{[['account', SignIn, '帳號與模型'], ['connections', Plugs, '工具與連線'], ['memories', Notebook, '專案記憶'], ['skills', PuzzlePiece, '研究技能'], ['preferences', GearSix, '一般設定']].map(([key, Icon, title]) => <button key={key} className={tab === key ? 'active' : ''} onClick={() => setTab(key)}><Icon size={17} />{title}</button>)}</nav><div className="settings-content page-scroll">{tab === 'account' ? <AccountPanel {...props} /> : tab === 'connections' ? <Connections {...props} /> : tab === 'memories' ? <Memories {...props} /> : tab === 'skills' ? <Skills {...props} /> : <Preferences {...props} />}</div></div>; }
